dist: trusty
sudo: required
language: php

services:
  - docker

php:
  - '7.0'
  - '7.1'
  - nightly

env:
  matrix:
    - DEPENDENCIES="low"
    - DEPENDENCIES="stable"

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install --prefer-source
  - if [ "$DEPENDENCIES" == "stable" ]; then composer update --prefer-stable; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --ansi --dry-run
  - ./vendor/bin/phpstan analyse src test --level 0

cache:
  directories:
    - $HOME/.composer/cache
